<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="four_wheel_bot">

  <!-- Parameters -->
  <xacro:property name="base_length" value="0.35"/>
  <xacro:property name="base_width"  value="0.25"/>
  <xacro:property name="base_height" value="0.10"/>

  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width"  value="0.02"/>

  <!-- Simple inertial macro -->
  <xacro:macro name="inertial_box" params="mass x y z">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <!-- crude inertia -->
      <inertia ixx="${(1/12)*mass*(y*y+z*z)}"
               iyy="${(1/12)*mass*(x*x+z*z)}"
               izz="${(1/12)*mass*(x*x+y*y)}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="inertial_cylinder" params="mass r h">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia ixx="${(1/12)*mass*(3*r*r + h*h)}"
               iyy="${(1/12)*mass*(3*r*r + h*h)}"
               izz="${(1/2)*mass*r*r}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </xacro:macro>

  <!-- Materials -->
  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>
  
  <material name="black">
    <color rgba="0.2 0.2 0.2 1.0"/>
  </material>

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="5.0" x="${base_length}" y="${base_width}" z="${base_height}"/>
  </link>

  <!-- Wheel macro -->
  <xacro:macro name="wheel" params="name x y">
    <link name="${name}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <xacro:inertial_cylinder mass="0.3" r="${wheel_radius}" h="${wheel_width}"/>
    </link>

    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}_link"/>
      <origin xyz="${x} ${y} ${wheel_radius}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Positions -->
  <xacro:property name="x_off" value="${base_length/2 - 0.03}"/>
  <xacro:property name="y_off" value="${(base_width/2) + (wheel_width/2) + 0.01}"/>

  <!-- 4 wheels -->
  <xacro:wheel name="front_left"  x="${ x_off}" y="${ y_off}"/>
  <xacro:wheel name="front_right" x="${ x_off}" y="${-y_off}"/>
  <xacro:wheel name="rear_left"   x="${-x_off}" y="${ y_off}"/>
  <xacro:wheel name="rear_right"  x="${-x_off}" y="${-y_off}"/>

</robot>
